### ISSUE TITLE
Cannot parse comments in an array block

### ISSUE THREAD

**Issue by gajus** [ota-meshi/yaml-eslint-parser#160]
Input:

```yaml
allowCompoundWords: true
ignorePaths:
  - node_modules
  - dist
  - pnpm-lock.yaml
  # The reason we are ignoring applicationsets is because the contents of it is
  # generated based on the names of the branches and auto-committed, i.e.
  # we cannot guarantee it does not contain misspellings.
  - applicationsets
  # This script contains bash color codes which confuse cspell.
  - './scripts/setup-test-cluster.sh'
```

Produces error:

```
/Users/gajus/Developer/contra/contra-cluster/cspell.yml
  6:3  error  Parsing error: Unexpected character '#'
```
